export const ErrorType = {
  AUTH_FAILURE_ERROR: "AUTH_FAILURE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  NO_ENTRY: "NoEntryError",
  NO_DATA: "NoDataError",
  BAD_REQUEST_ERROR: "BAD_REQUEST_ERROR",
  FORBIDDEN_ERROR: "FORBIDDEN_ERROR",
  BAD_GATEWAY: "BadGatewayError",
} as const