export const ErrorType = {
  AUTH_FAILURE_ERROR: "AUTH_FAILURE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  NO_ENTRY: "NO_ENTRY_ERROR",
  NO_DATA: "NO_DATA_ERROR",
  BAD_REQUEST_ERROR: "BAD_REQUEST_ERROR",
  FORBIDDEN_ERROR: "FORBIDDEN_ERROR",
} as const